version: "3"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: "backend"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: "frontend"
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: timescale/timescaledb:latest-pg12
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=netdash
      - POSTGRES_PASSWORD=netdash
