version: "3"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: "backend"
    networks:
      - backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: "frontend"
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend

networks:
  backend:
