###
POST http://localhost:8080/api/query
Content-Type: application/json

{
	"query": "select name, username from datasources",

	"mapping": [
		{
			"source": "name",
			"target": "x"
		},
		{
			"source": "username",
			"target": "y"
		}
	],
	"datasourceId": 7
}

