###
POST http://localhost:8080/api/query
Content-Type: application/json

{
	"query": "select name, type, url from datasources where id = :id",
	"queryParameters": {
		"id": 5
	},
	"mapping": [
		{
			"source": "name",
			"target": "x"
		},
		{
			"source": "type",
			"target": "y"
		},
        {
            "source": "url",
            "target": "z"
        }
	],
	"datasourceId": 7
}

